version: '3'

services:
  influxdb:
    image: opnfv/barometer-influxdb
    network_mode: host
    volumes:
      - /var/lib/influxdb
  grafana:
    image: opnfv/barometer-grafana
    network_mode: host
    volumes:
      - /var/lib/grafana
