---
collectd_plugins: []
collectd_interval: "{{ interval_value }}"
collectd_hostname: "{{ inventory_hostname }}"

collectd_plugin_capabilities_port: "9564"

collectd_plugin_csv_datadir: "{{ csv_log_dir }}"
collectd_plugin_csv_storerates: False

collectd_plugin_dpdk_telemetry_client_socket_path: "/var/run/.client"
collectd_plugin_dpdk_telemetry_dpdk_socket_path: "/var/run/dpdk/rte/telemetry"

collectd_plugin_exec_exec:
  - user: "collectd_exec"
    exec: "/src/barometer/src/collectd/collectd_sample_configs/ovs_pmd_stats.sh"
collectd_plugin_exec_notification:
  - user: "collectd_exec"
    notification_exec: "/src/barometer/src/collectd/collectd_sample_configs/write_notification.sh"

collectd_plugin_hugepages_report_per_node_hp: True
collectd_plugin_hugepages_report_root_hp: True
collectd_plugin_hugepages_values_pages: True
collectd_plugin_hugepages_values_bytes: False
collectd_plugin_hugepages_values_percentage: False

collectd_plugin_intelpmu_reporthardwarecacheevents: True
collectd_plugin_intelpmu_reportkernelpmuevents: True
collectd_plugin_intelpmu_reportsoftwareevents: True
collectd_plugin_intelpmu_cores: ["0-4"]

collectd_plugin_logfile_loglevel: "{{ logfile_log_level }}"
collectd_plugin_logfile_file: "{{ logfile_dir }}/collectd.log"
collectd_plugin_logfile_timestamp: True

collectd_plugin_write_prometheus_port: 9103

collectd_plugin_syslog_loglevel: "info"
