# Copyright 2018-2019 Intel Corporation and OPNFV. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---

- name: install mcelog package
  package:
     name: mcelog
     state: present
  ignore_errors: "true"
  when: install_mcelog|default(false)|bool
  tags:
     - mcelogs

- name: check if mcelog present
  shell: which mcelog > /dev/null
  register: mcelog_present
  ignore_errors: "true"
  when: install_mcelog|default(false)|bool
  tags:
     - mcelogs

- name: build mcelog from sources if not in package
  import_tasks: make_mcelog.yml
  when: (mcelog_present is failed) and (install_mcelog|default(false)|bool)
  tags:
     - mcelogs

- name: start mcelog daemon if not running
  service:
     name: mcelog
     state: started
     enabled: true
  ignore_errors: "true"
  when: install_mcelog|default(false)|bool
  tags:
     - mcelogs

- name: check if mcelog running on host
  shell: ps -ef | grep mcelog | grep -v grep > /dev/null
  register: mcelog_running
  ignore_errors: "true"
  tags:
    - mcelogs

- name: check if mcelog exists
  shell: which mcelog > /dev/null
  register: mcelog_exists
  ignore_errors: "true"
  tags:
    - mcelogs

- name: check if mcelog-client exists
  stat:
    path: /var/run/mcelog-client
  register: mcelog_client_exists
  ignore_errors: "true"
  tags:
   - mcelogs

- name: enable mcelog plugin
  template:
    src: mcelog.conf.j2
    dest: "{{ config_file_dir }}/mcelog.conf"
  when: (mcelog_running is succeeded) and (mcelog_exists is succeeded) and (mcelog_client_exists is succeeded)
  tags:
          - mcelogs
