version: '2'

services:
  influxdb:
    image: influxdb:1.3.7
    network_mode: host
    volumes:
      - /var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro
  grafana:
    image: grafana/grafana:4.6.0
    network_mode: host
    volumes:
      - /var/lib/grafana

