version: '3'

services:
  zookeeper:
    image: 31z4/zookeeper
    network_mode: host
    ports:
     - 2181:2181
  kafka:
    image: barometer-kafka
    network_mode: host
    ports:
     - 9092:9092
  ves:
    image: barometer-ves
    network_mode: host
    command: native.yaml


